### ISSUE TITLE
chore: database

### ISSUE THREAD

**Issue by felipesaldata** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#1]
### Summary 💡
At this task we set the configuration of the data model and all the related requirements of the databases management.

### Acceptance Criteria
- [x] Entity-Relation diagram of Kaggle's Dataset.
- [ ] Define the external data to extract and link with the project.
- [ ] Update the entity-relation diagram with the given and extracted data sources.
- [x] #24
- [ ] Set the roles for the project.

**Comment by nazlonga** [comment]
I think the second acceptance criteria is the result of the previous issue. So here we need to be more specific about what we need from that output

**Comment by nazlonga** [comment]
If there is already an output of the ER diagram, here you can also share it

**Comment by felipesaldata** [comment]
This issue were separated in others, i proceed to close it
