### ISSUE TITLE
chore: Entity-Relation diagram of given dataset.

### ISSUE THREAD

**Issue by danieldhats7** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#11]
### Sumary 💡
Define entity-relation diagram of given dataset.

### Acceptance Criteria
- [x] Get data from kaggle resource.
- [x] Understand the data and the relationships between them.
- [x] Check data normalization.
- [x] Make the entity-relation diagram.

**Comment by danieldhats7** [comment]
Avoid [Bad Practices in Database Design](https://www.toptal.com/database/database-design-bad-practices)

**Comment by felipesaldata** [comment]
Proceed to close this issue by having all the requirements completed
