### ISSUE TITLE
feat: Understand all the available data at the given dataset.

### ISSUE THREAD

**Issue by alexrods** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#15]
## Summary
For search new external data, we need to know the content and context of original data.

### Acceptance Criteria

- [x] Create a entity-relation table and the content of each table.

**Comment by alexrods** [comment]
## About Dataset:

- The Brazilian ecommerce public dataset of orders made at [Olist Store](http://www.olist.com/) (the largest department store in Brazilian marketplaces)
- The dataset has information of 100k orders from 2016 to 2018 made at multiple marketplaces in Brazil.
- Its features allows viewing an order from multiple dimensions: from order status, price, payment and freight performance to customer location, product attributes and finally reviews written by customers. 

### In concrete the content of tables is:
- **olist_customer_dataset:** Content customer information as city, state and zip code.
- **olist_geolocation_dataset:** Here we can find the geolocation information of customer and sellers as city, state, latitude and longitude.
- **olist_order_items_dataset:** This table contents the information of items bought/sold, includes number of items, price of unitary item, freight value, and who is seller.
- **olist_order_payments_dataset:** This table contents the payment method, fees number, and payment value.
- **olist_order_reviews_dataset:** Here is the customer reviews of articles bought, contents a score, review comments and answers to reviews.
- **olist_orders_dataset:** In this table we can find the status of orders, and information about date of purchase, approved date, delivered date and delivery estimated date, ***Can create the days to delivery column***.
- **olist_products_dataset:** This table contents the product information, its category, length of product name and product description, its physical characteristics too. ***Exist corretation between product size with freight value and days to delivery?***
- **olist_sellers_dataset:** Here is the seller information as zip code, city and state.
- **product_category_name_translation:** This table give us information about categories in **olist_products_dataset**, in a fast inspection it have redundancy in some categories.

The original ER diagram of this dataset is:

![](https://drive.google.com/uc?id=1FzpgeuYn_lDmklenuwjhGK8x8RfOTjxZ)

New [ER diagram](https://github.com/C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce/blob/main/er_diagram.md).

### The finality of search external data is compare the reviews between category products with others e-commerce, then need to normalize the category names.

**Comment by felipesaldata** [comment]
issue completed and deployed at the csv_analysis branch for the continuity
