### ISSUE TITLE
chore: Design the webscraping strategy to extract the information.

### ISSUE THREAD

**Issue by alexrods** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#17]
## Summary

Set the tools for data extraction through web scrapping

### Acceptance Criteria

- [x] Select the language to use
- [x] Select the libraries to use
- [x] Select the pages to which to do web scraping

**Comment by GabyGO2108** [comment]
For this issue we decided to go with our favorite language, Python. The reasons, well: 
1. It's simplicity 
2. It has a large amount of libraries 
3. Timely saving
4. The syntax is easily understood
5. Familiarity- the entire team is familiarized with it

As for the libraries, we first thought about using Scrapy and LXML for their power and simplicity. We'll see if  they are enough, or changes will need to be made.

**Comment by alexrods** [comment]
- The Web Scraping was made using _requests_ and _lxml_ libraries on **Mercado Livre Brazil**
- The strategy is: 
 1- Define categories to scrape.
 2- Collect the link of those categories.
 3- Collect the link of each product of each category.
 4- Scrape reviews for each product.
