### ISSUE TITLE
chore: External Data

### ISSUE THREAD

**Issue by felipesaldata** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#2]
### Summary 💡
Stablishment of the external data to incluide at the model, the webscrapping strategies to extact it and the upload to the project dataset.

### Acceptance Criteria
- [x] #4
- [x] #14
- [ ] Adjust the data model with the extracted data.
- [ ] Design the webscrapping strategy to extract the information.
- [ ] Build and run the scripts to scrap the data.
- [ ] Clean and transform the data to the structure required for the data model.
- [ ] Load the data to the project's database.
- [ ] validate the integrity of the data uploaded.

**Comment by nazlonga** [comment]
@felipesalda please divide this issue into the corresponding subtasks, and assign the people working on it.

**Comment by felipesaldata** [comment]
This issue were separated in others as @nazlonga suggested, i proceed to close it
