### ISSUE TITLE
chore: Validate the integrity of the data uploaded.

### ISSUE THREAD

**Issue by alexrods** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#22]
## Summary

Validate the integrity  of the data for future analysis

### Acceptance Criteria

- [ ] Process with redundant data 
- [ ] Process with missing data 
- [ ] Standardize data types (string, float, category, datetime, int,)
- [ ] Automate

**Comment by larispardo** [comment]
Was this finished?

**Comment by elyager** [comment]
This task is not relevant anymore
