### ISSUE TITLE
chore: Set the framework for data analysis.

### ISSUE THREAD

**Issue by GabyGO2108** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#23]
### Summary 💡

Set the languages, libraries and frameworks for the data analysis

### Acceptance Criteria

- [x]  Define the general  working framework used in data analysis within the context of data science (Platzi's Data Science School)  
- [x]  Look in Kaggle if the data base for the project has any programming language used by peers for data analysis
- [x]  Define the programming language the team is most familiarized with 
- [x]  Choose the programming language based on a team consensus
- [x] Define the packages and libraries that are going to be used based on the previews points
- [x]  Define the scope of the project

**Comment by GabyGO2108** [comment]
This issue contains the criteria for choosing the programming language(s) to be used for the data analysis step of the project.

**Comment by GabyGO2108** [comment]
The programming language we'll be using based on the acceptance criteria, is Python, with these libraries (Numpy, Pandas, matplotlib, seaborn and sklearn), and this package for NLP (Natural Language Toolkit -NLTK-).

As for the scope, it will be as follows:
- Make the table for the historical data of the transactions, make the proper comparisons of the "product_category_name" with other e-commerce(s), and the analysis of the comments of the reviews and the scores of said reviews.

**Comment by felipesaldata** [comment]
Issue completed 😁
