### ISSUE TITLE
chore: Project Technology

### ISSUE THREAD

**Issue by felipesaldata** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#3]
### Summary 💡
Determining the technologies, frameworks, languages, and libraries to use at every component of the project.

### Acceptance Criteria
- [x] #5
- [x] Define the Data model and Data Pipeline of the project.
- [x] Select the provider for the hosting of the projects features (cloud computing service).
- [x] Establish the technique to connect the databases queries to the data analysis.
- [x] Set the languages, libraries and frameworks for the data analysis.
- [x] Select the data visualization framework to share the analyzed data and transactions summary.

**Comment by nazlonga** [comment]
@felipesalda the acceptance criteria of this task are actual subtasks. 
I recommend dividing this issue into smaller ones, so we can really close it when we are done, instead of having this one open for too long.

**Comment by felipesaldata** [comment]
This issue were separated in others as @nazlonga suggested, i proceed to close it.
