### ISSUE TITLE
chore: Define the Entity Relation Diagrama

### ISSUE THREAD

**Issue by felipesaldata** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#6]
### Summary 💡
Determine the structure of the ER Diagram of the project.

### Acceptance Criteria
- [x] Set the types of relations.
- [x] Define the keys.
- [x] Normalization of the variables.
- [x] Set the Entities and attributes of the model.

**Comment by danieldhats7** [comment]
# ER diagram
Hello, I wanted to make a contribution to this issue. this is what I have in mind about the ER diagram.

![E-commerce_ERD](https://user-images.githubusercontent.com/69657612/161407546-1049e279-b928-47a4-8843-b057c0c8198c.jpeg)

## Changes
* All tables were renamed to avoid redundancies.
* All tables's columns were renamed to avoid redundancies.
* All indexes to type `int` to improve query performance.

### olist_customers_dataset
* Remove the `customer_id` column to normalize the table.
* Convert `customer_unique_id` column to `id` column of type `int`.
* Add the `name` and `last_name` columns to represent a more realistic environment.

### olist_order_items_dataset
* Remove `order_item_id` column and add `quantity` column for normalization.
* All values in the `freight_value` column should be updated by `quantity` * old value of `freight_value`.

## Observations and suggestions
* It would be pertinent to replace the `name_length` and `description_length` columns with `name` and `description` respectively in the `products` table and generate random values to simulate a more realistic environment.
* **Creo** que debemos prestar especial atención a la tabla `order_items` ya que pienso que tener 3 llaves foraneas en una sola tabla no es del todo una buena practica.
* Ademas, ya que para cada producto tiene su `seller_id` y `price` correspondientes, estos, podemos agregarlos a la tabla `products`.
* Podemos agregar una columna `total` para cada orden.

**Comment by GabyGO2108** [comment]
Hi team! Atendí algunas de las observaciones y sugerencias. Reconozco que no tengo mucha experiencia con los diagramas ER, entonces no entendí bien qué hacer con las llaves foráneas. Dejo por aquí un archivo editable en donde ya vienen las relaciones que creo pudieran corresponder, partiendo del increíble trabajo que Daniel hizo. Sientánse libres de borrar, mover, corregir, etc. el diagrama. Seguro hay  mejoras que hacer y mejores herramientas, pero por el momento Excel me sacó del apuro.

Saludos
[Diagrama ER.xlsx](https://github.com/C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce/files/8412554/Diagrama.ER.xlsx)
s

**Comment by felipesaldata** [comment]
Thank you soo much @danieldhats7 and @GabyGO2108  for your contribution, i'll integrate the ER Diagram and your suggestions to the [project_technology.md](https://github.com/C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce/blob/main/project_technology.md) at the main branch.

With this properties clear we can create the database and make test by queries if the foreing keys at `order_items`  or the others gave us errors 🦾.

**Comment by felipesaldata** [comment]
Issue completed, ER diagram chore updated at [project_technology.md](https://github.com/C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce/blob/main/project_technology.md) 🏋🏻‍♂️
