### ISSUE TITLE
feat: Graph 2. Total of sales and categories

### ISSUE THREAD

**Issue by leopensaa** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#62]
### 💡 Goal
Show the total of sales made per year during the study period (2016-2018) including their products category.

### 🤝 Acceptance Criteria
- [x]  bar graph or similar with total sales per year
- [x]  categories of best-selling products of each year

See the [Notion ](https://cumbersome-gorgonzola-9a1.notion.site/Sprint-8-GitHub-issues-25f830dd17114e52a105da679e4da4f0)reference with pictures as example

**Comment by felipesaldata** [comment]
Here is the solution for this issued graph

```python
total_sales_categories_year = products_df[['order_id','purchase_year','price','product_category_name_english']]
top5_cat_year = total_sales_categories_year.groupby(['purchase_year','product_category_name_english'],as_index=False).agg({'price':'sum'}).sort_values(by=['purchase_year','price'], ascending=False)
top5_cat_year = top5_cat_year.groupby('purchase_year').head(5).reset_index(drop=True)
top5_cat_year

fig = px.bar(top5_cat_year,x='purchase_year',y='price',color='product_category_name_english')
fig.show()
```


Resulting chart
![Image](https://user-images.githubusercontent.com/46731424/171872398-8060b106-d36e-4a64-8ff3-869185e388dc.png)

Notice that the amount of purchases of 2016 is not comparable with the others, and also has different top 5 categories:
(this can be seeing by zooming the plotly chart
![Image](https://user-images.githubusercontent.com/46731424/171873200-fc6fd20c-91e3-4667-a781-10ca90ec28a3.png)
