### ISSUE TITLE
feat: Graph 5. Delivery performance

### ISSUE THREAD

**Issue by leopensaa** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#65]
### 💡 Goal

Show the % of orders that arrived on time and late.

### 🤝 Acceptance Criteria

- [x]  keep the pie chart display
- [x]  improve texts by enlarging the font of the % of deliveries on time versus late
- [x]  follow a standard color palette for the entire dashboard

See the [Notion ](https://cumbersome-gorgonzola-9a1.notion.site/Sprint-8-GitHub-issues-25f830dd17114e52a105da679e4da4f0)reference with pictures as example

**Comment by felipesaldata** [comment]
This is a minor detail to take in count as we define the palette for the dashboard
