### ISSUE TITLE
feat: Graph 7. Churn insight

### ISSUE THREAD

**Issue by leopensaa** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#67]
### 💡 Goal

Show the volume of unique buyers and repeat buyers.

### 🤝 Acceptance Criteria

- [x]  keep table display
- [x]  number of purchases made per customer (highlight the 96.9%)
- [x]  change column names to “Order count”, “Costumers” and “Costumers percentage”, respectively
- [x]  add “%” sign to Customers percentage and decrease to a decimal
- [x]  add "." to the thousands in the Customers column
- [x]  exclude the data that are ≥5 purchases, as they are very isolated cases of few customers

See the [Notion ](https://cumbersome-gorgonzola-9a1.notion.site/Sprint-8-GitHub-issues-25f830dd17114e52a105da679e4da4f0)reference with pictures as example.

**Comment by felipesaldata** [comment]
Final AC gets completed by saving the dataframe head like this:

```python
customer_counter.head(5)
```
