### ISSUE TITLE
feat: Graph 8. Preferred payment methods

### ISSUE THREAD

**Issue by leopensaa** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#68]
### 💡 Goal

Show the % distribution of payment methods.

### 🤝 Acceptance Criteria

- [x]  keep pie chart display
- [x]  improve texts by enlarging the font. Delete separations with “_”.
- [x]  follow a standard color palette for the entire dashboard

See the [Notion ](https://cumbersome-gorgonzola-9a1.notion.site/Sprint-8-GitHub-issues-25f830dd17114e52a105da679e4da4f0)reference with pictures as example.

**Comment by felipesaldata** [comment]
This is a minor detail to take in count as we define the palette for the dashboard
