### ISSUE TITLE
feat: Graph 9. Machine learning insight

### ISSUE THREAD

**Issue by leopensaa** [C10-Brazilian-e-commerce-modeling-team/brazilian-e-commerce#69]
### 💡 Goal

//add text here.

### 🤝 Acceptance Criteria

- [x]  //add text here
- [x]  //add text here
- [x]  //add text here

See the [Notion ](https://cumbersome-gorgonzola-9a1.notion.site/Sprint-8-GitHub-issues-25f830dd17114e52a105da679e4da4f0)reference with pictures as example.

**Comment by felipesaldata** [comment]
Issue completed and implemented on the repo
